#!/bin/zsh

cd $(dirname $0)

for d in home/**/*(/D)
do
    mkdir -p $HOME/${d#home/}
done

for f in home/**/*(.D)
do
    echo ln -sf "${f:a}" $HOME/${f#home/}
    ln -sf "${f:a}" $HOME/${f#home/}
done
